config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    resources :comments
  end

  get 'browse', to: 'posts#browse', as: :browse_posts

  devise_for :users, :controllers => { registrations: 'home' }

  get ':user_name', to: 'profiles#show', as: :profile

  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  post 'relationships/follow_user', to: 'relationships#follow_user', as: :follow_user

  post 'relationships/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates_presence_of :user_id, :post_id

  belongs_to :user
  belongs_to :post

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  validates_presence_of :following_id, :follower_id
  validates_uniqueness_of :following_id, scope: :follower_id

  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates_presence_of :image, :user_id

  has_attached_file :image, styles: { :medium => '640x640>', :small => '400x400>'}
  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|png|gif)$/, message: 'is invalid.'

  scope :of_followed_users, -> (following_users) { where user_id: following_users }

  belongs_to :user
  has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, styles: { medium: '640x640#', small: '100x100#', thumb: '50x50#' }
  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|png|gif)$/, message: 'is invalid.'

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_post

  def index
    respond_to do |format|
      format.html {redirect_to root_path}
      format.js { render :load_all, :locals => {:post => @post} }
    end
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id

    @comment.save
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render :create, :locals => {:comment => @comment, :post => @post} }
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if (@comment.user == current_user)
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render :destroy, :locals => {:comment => @comment, :post => @post} }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/home_controller.rb
class HomeController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = (Post.of_followed_users(current_user.following) + current_user.posts).sort_by(&:created_at).reverse!
  end

  def browse
    @posts = Post.all.order('created_at DESC')
    render :browse, :local => {:posts => @posts}
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @post.update(edit_params)
    redirect_to @post
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def edit_params
    params.require(:post).permit(:caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    if current_user != Post.find(params[:id]).user
      redirect_to posts_path
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]

  def show
    @posts = @user.posts.order('created_at DESC')
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      redirect_to profile_path(@user.user_name)
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:image)
  end

  def owned_profile
    unless current_user == @user
      redirect_to profile_path(@user.user_name)
    end
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user!

  def follow_user
    @user = User.find_by(user_name: params[:user_name])
    if current_user.follow @user.id
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js {render :follow_user, :locals => {:user => @user}}
      end
    end
  end

  def unfollow_user
    @user = User.find_by(user_name: params[:user_name])
    if current_user.unfollow @user.id
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js {render :unfollow_user, :locals => {:user => @user}}
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_image_select(user)
    return image_tag user.image.url(:small) if user.image.exists?
    image_tag 'default_image.png'
  end

  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/comments/_comment.html.erb
<tr id="comment_<%= post.id %>_<%= comment.id %>"><td><%= link_to comment.user.user_name, profile_path(comment.user.user_name) %></td>
  <td><%= comment.content %></td>
  <% if comment.user == current_user %>
    <td><%= link_to 'x', post_comment_path(post, comment), method: 'delete', remote: true %></td>
  <% end %>
</tr>

app/views/comments/_load_all.html.erb
<table id="comments_<%= post.id %>">
  <% post.comments.each do |comment| %>
    <%= render :partial => 'comments/comment', :locals => {:comment => comment, :post => post} %>
  <% end %>
</table>

app/views/comments/create.js.erb
$('#comments_<%= post.id %>').append('<%= j render :partial => 'comment', :locals => {:comment => comment, :post => post} %>');
$('#comment_content_<%= post.id %>').val('');

app/views/comments/destroy.js.erb
$('#comment_<%= post.id %>_<%= comment.id %>').remove();

app/views/comments/load_all.js.erb
$('#comments_<%= post.id %>').replaceWith('<%= j render :partial => 'load_all', :locals => { :post => post } %>');
$('#comments_paginator_<%= post.id %>').hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fotobook | <%= content_for?(:title) ? yield(:title) : "Image sharing web app" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body align="center">
    <div id="header">
      <% if user_signed_in? %>
        <div id="left-navbar">
          <ul id="nav-ul">
            <li id="nav-li"><%= link_to_unless_current "Home", root_url %></li>
            <li id="nav-li"><%= link_to_unless_current current_user.user_name, profile_path(current_user.user_name) %></li>
            <li id="nav-li"><%= link_to_unless_current "Browse", browse_posts_path %></li>
            <li id="nav-li"><%= link_to_unless_current "New Post", new_post_path %></li>
          </ul>
        </div>
        <div id="right-navbar">
          <ul id="nav-ul">
            <li id="nav-li"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </div>
      <% else %>
        <h3>Share your photos with your friends!</h3>
      <% end %>
      <h1>Fotobook</h1>
    </div>

    <div id="container">
      <% flash.each do |name, msg| %>
        <% if msg.include? "Invalid" %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div align="center">

  <div id="time-ago" style="font-size: smaller; color: gray">
    <%= time_ago_in_words post.created_at %>
  </div>

  <%= post.caption %><br>

  <% if post.user == current_user %>
      <%= link_to (image_tag post.image.url(:medium)), edit_post_path(post) %>
  <% else%>
      <%= image_tag post.image.url(:medium) %>
  <% end %>

  <table id="comments_<%= post.id %>">
    <% if post.comments.any? %>

      <div id="comments_paginator_<%= post.id %>">
        <% if post.comments.count > 4 %>
          <br><%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true %>
        <%end %>
      </div>

      <% post.comments.last(4).each do |comment| %>
        <%= render :partial => 'comments/comment', :locals => {:comment => comment, :post => post} %>
      <% end %>

    <% end %>
  </table>

  <%=form_for [post, post.comments.new], remote: true do |f| %>
      <br><%= f.text_field :content, placeholder: 'Add a comment...', id: "comment_content_#{post.id}", size: "86" %><br>
  <% end %>

</div>

app/views/posts/_post_dashboard.html.erb
<div align="center">

  <% @posts.each do |post| %>
      <%= link_to post.user.user_name, profile_path(post.user.user_name) %><br>
      <%= render :partial => 'post', :locals => {:post => post} %>
      <hr>
  <% end %>

  <% if !@posts.any? %>
    <h4 style="color: cadetblue">Welcome to fotobook!</h4><br><br>
      Share your photos by creating a new post!<br><br>
      Browse what other users have shared!
  <% end %>

</div>

app/views/posts/browse.html.erb
<div id="photo-grid">

    <% @posts.each do |post| %>

      <div id="photo">
        <%= link_to post.user.user_name, profile_path(post.user.user_name) %><br>
        <%= link_to (image_tag post.image.url(:small)), post_path(post) %>
      </div>

    <% end %>

  <% if !@posts.any? %>
      <h4 style="color: cadetblue">Welcome to fotobook!</h4><br><br>
      Share your photos by creating a new post!<br><br>
      Browse what other users have shared!
  <% end %>

</div>

app/views/posts/edit.html.erb
<div align="center">

  <b>Edit Post</b><br>

  <%= image_tag @post.image.url(:medium) %><br>

  <%= form_for @post, :html => {:multipart => true} do |form| %>
      <%= form.label :caption %><br>
      <%= form.text_area :caption, size: "100" %><br>
      <%= form.submit %>
  <% end %>
  <br>

  <%= link_to 'Delete Post', post_path(@post), method: 'delete', data: { confirm: "Are you sure you want to delete this post?"}  %>
  <%= link_to 'Cancel', post_path(@post), method: 'get' %>

</div>

app/views/posts/index.html.erb
<%= render :partial => 'post_dashboard', :locals => {:posts => @posts} %>

app/views/posts/new.html.erb
<div align="center">
    <b>Create New Post</b><br><br>

    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |message| %>
          <%= message %>
      <% end %><br><br>
    <% end %>

    <%= form_for @post, :html => {:multipart => true} do |form| %>
        <%= form.label :image %><br>
        <%= form.file_field :image, :required => true%><br><br>
        <%= form.label :caption %><br>
        <%= form.text_area :caption, size: "50" %><br>
        <%= form.submit %>
    <% end %>
    <br>

    <%= link_to 'Cancel', posts_path, method: 'get' %>
</div>

app/views/posts/show.html.erb
<div align="center">
  <%= link_to @post.user.user_name, profile_path(@post.user.user_name) %><br>
  <%= render :partial => 'post', :locals => {:post => @post} %>

  <% if @post.user == current_user %>
      <%= link_to 'Edit Post', edit_post_path(@post), method: 'get' %>
  <% end %>

</div>

app/views/profiles/edit.html.erb
<div align="center">

  <b>Edit Profile</b><br><br>

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
  <% end %>

  <%= profile_image_select(@user) %><br>

  <%= form_for @user, url: {action: "update"}, :html => {:multipart => true} do |form| %>
      <%= form.label :image %><br>
      <%= form.file_field :image, :required => true%><br><br>
      <%= form.submit %>
  <% end %>
  <br>

  <%= link_to 'Cancel', profile_path(@user.user_name), method: 'get' %>

</div>

app/views/profiles/show.html.erb
<%= @user.user_name %><br>

<div id="profile"><%= profile_image_select(@user) %></div><br>

<% if @user == current_user %>
  <%= link_to 'Change Profile Picture', edit_profile_path(@user.user_name) %>
<% else %>
  <% if current_user_is_following(current_user.id, @user.id) %>
      <%= render :partial => 'relationships/unfollow_user', :locals => {:user => @user} %>
  <% else %>
      <%= render :partial => 'relationships/follow_user', :locals => {:user => @user} %>
  <% end %>
<% end %>

<hr>

<% @posts.each do |post| %>
    <%= render :partial => 'posts/post', :locals => {:post => post} %>
    <hr>
<% end %>

app/views/relationships/_follow_user.html.erb
<div id="follow_button"><%= button_to 'Follow', follow_user_path, remote: true, method: :post, params: { user_name: @user.user_name } %></div>

app/views/relationships/_unfollow_user.html.erb
<div id="unfollow_button"><%= button_to 'Following', unfollow_user_path, remote: true, id: 'unfollow_button', method: :post, params: { user_name: @user.user_name } %></div>

app/views/relationships/follow_user.js.erb
$('#follow_button').replaceWith('<%= j render :partial => 'unfollow_user', :locals => {:user => @user} %>');

app/views/relationships/unfollow_user.js.erb
$('#unfollow_button').replaceWith('<%= j render :partial => 'follow_user', :locals => {:user => @user} %>');